on: workflow_dispatch
jobs:
  build-all:
    runs-on: ubuntu-22.04
    env:
      openwrt_version: 0b54029a6e96bb2ce484f316be3870cc2617de30
    strategy:
      matrix:
        include:
          - subtarget: stm32mp1
            profile: stm32mp157f-dk2
          - subtarget: stm32mp1
            profile: stm32mp157f-dk2-demo
          - subtarget: stm32mp1
            profile: stm32mp135f-dk
          - subtarget: stm32mp1
            profile: stm32mp135f-dk-demo
          - subtarget: stm32mp2
            profile: stm32mp257f-ev1
          - subtarget: stm32mp2
            profile: stm32mp257f-ev1-demo
          - subtarget: stm32mp2
            profile: stm32mp257f-dk
          - subtarget: stm32mp2
            profile: stm32mp257f-dk-demo

    steps:
      - uses: actions/checkout@v4
        with:
          path: openwrt-feed-st
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: ${{ env.openwrt_version }}
          path: openwrt
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pyelftools python3-cryptography python3-setuptools python3-pil python3-dev
          sudo apt install -y device-tree-compiler swig
      - name: Add ST feed
        run: echo src-link st /home/runner/work/openwrt-feed-st/openwrt-feed-st/openwrt-feed-st >> openwrt/feeds.conf.default
      - name: Update feeds
        run: cd openwrt; ./scripts/feeds update -a
      - name: Install stm32 target
        run: cd openwrt; ./scripts/feeds install -f stm32
      - name: Install all other feeds
        run: cd openwrt; ./scripts/feeds install -a -f
      - name: Configure
        run: |
          printf "CONFIG_TARGET_stm32=y\\nCONFIG_TARGET_stm32_${{ matrix.subtarget }}=y\\nCONFIG_TARGET_stm32_${{ matrix.subtarget }}_DEVICE_${{ matrix.profile }}=y\\n" > openwrt/.config
          make -C openwrt defconfig
      - name: Build
        id: build
        run: make -j4 -C openwrt || make -C openwrt -j1 V=s
      - name: 'Archive factory image'
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-stm32-${{ matrix.subtarget }}-${{ matrix.profile }}-ext4-factory.img.gz
          path: openwrt/bin/targets/stm32/${{ matrix.subtarget }}/openwrt-stm32-${{ matrix.subtarget }}-${{ matrix.profile }}-ext4-factory.img.gz
      - name: 'Archive sysupgrade image'
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-stm32-${{ matrix.subtarget }}-${{ matrix.profile }}-ext4-sysupgrade.img.gz
          path: openwrt/bin/targets/stm32/${{ matrix.subtarget }}/openwrt-stm32-${{ matrix.subtarget }}-${{ matrix.profile }}-ext4-sysupgrade.img.gz
